# Generated by Django 2.2.7 on 2020-03-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='', max_length=100)),
                ('omschrijving', models.TextField()),
                ('categorie', models.CharField(max_length=20)),
                ('ingredient', models.TextField()),
                ('afbeelding', models.ImageField(upload_to='media')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
